### ISSUE TITLE
Export more types from @fetch-mock/core

### ISSUE THREAD

**Issue by brucespang** [wheresrhys/fetch-mock#760]
Hi!

First of all, really excited that you've made some changes to fetch-mock lately! I'm looking forward to upgrading us to 10.x, and have run into some issues with types. I'm very happy to submit a PR, but would like to know whether the change is intentional or not before I do.

Previously, we were using fetch-mock with:

```typescript
import { MockResponse, MockResponseFunction, MockRequest, MockResponseObject } from 'fetch-mock';
```

With 10.1.1, this gives the error `Module '".."' has no exported member 'MockResponse'. Did you mean to use 'import MockResponse from ".."' instead?` and we would need to work around it by doing:
```typescript
import fetchMock from 'fetch-mock';
type MockResponse = fetchMock.MockResponse;
```

It's not entirely clear to me whether this was a desired API change (esp. since you don't use typescript :)). If it wasn't, I am happy to send in a PR to fix it.

Thanks so much!

**Comment by wheresrhys** [comment]
I didn't actually change the types aside from one or two lines related to ESM vs commonjs. Someone raised a bug with that which I thought was fixed last week https://github.com/wheresrhys/fetch-mock/issues/726.

What toolchain are you using? (typescript version, esm or commonjs, node version, testing framework)

**Comment by brucespang** [comment]
It seems like this was introduced by 9ffba4019b76cd9899420e3a4f8ac3e3b3d42237 (switching from `export =` to `export default`). To reproduce, you should be able to add `import { MockRequest } from '..';` to the top of fetch-mock-tests.ts. For me, it compiles without problem with tsc 5.5.4 on commit ae1573996256a4ec1db05aa30452ebe80fdd3b33. Once I switch to 9ffba4019b76cd9899420e3a4f8ac3e3b3d42237, I run into the error

```
$ tsc types/fetch-mock-tests.ts
types/fetch-mock-tests.ts:2:10 - error TS2614: Module '".."' has no exported member 'MockRequest'. Did you mean to use 'import MockRequest from ".."' instead?

2 import { MockRequest } from '..';
           ~~~~~~~~~~~


Found 1 error in types/fetch-mock-tests.ts:2
```

I've tried a few ways to get `index.d.ts` to export all three of the namespace fetchMock, the constant fetchMock, and the individual types, but haven't been able to do it without repeating a whole bunch of code in index.d.ts (e.g. adding an `export type MockRequest = fetchMock.MockRequest;` to the bottom of index.d.ts). Happy to send over a PR that does that or anything else you suggest, or we can just update our import statements!

**Comment by wheresrhys** [comment]
I think I'll unfortunately have to ask you to update your import statements. I tweaked the types a few times in response to feedback and now it does seem that it's compatible with all the combinations of typescript/js x esm/commonjs, so I don't really want to fiddle any more, or give myself more lines of type definitions to maintain

**Comment by wheresrhys** [comment]
I wonder if you can share details of why you're importing MockResponse etc from fetch-mock? As these are interfaces, rather than classes, I would have assumed that a) you don't need to instantiate them directly and b) the typechecker is able to point you at the definitions whenever you enter invalid values into .mock()

As I don't use typescript in my applications perhaps there is something that I'm misunderstanding about what typescript users of fetch-mock need

**Comment by wheresrhys** [comment]
I'm gonna reopen this to remind me to think about it for the next version

**Comment by wheresrhys** [comment]
@fetch-mock/core now exports a lot more stuff - hopefully going forward it hits the right balance, and as the codebase is written in typescript, exporting extra things as and when users need them is more straightforward
